create table Customer
(
    id       int primary key generated by default as identity,
    username varchar(50) not null,
    balance  double precision check ( balance > 0 )
);

create table Orders
(
    id           int primary key generated by default as identity,
    total_amount double precision,
    customer_id  int references Customer (id) on delete cascade
);

create table Product
(
    id           int primary key generated by default as identity,
    product_name varchar(100) not null,
    price        double precision,
    quantity     int
);

insert into Customer (username, balance)
VALUES ('Margarita', 12000);
insert into Customer (username, balance)
VALUES ('Miron', 7000);
insert into Customer (username, balance)
VALUES ('Alena', 8000);


insert into Product(product_name, price, quantity)
VALUES ('cup', 100, 50);
insert into Product(product_name, price, quantity)
VALUES ('mouse', 800, 70);
insert into Product(product_name, price, quantity)
VALUES ('paper', 500, 40);
insert into Product(product_name, price, quantity)
VALUES ('toy', 300, 15);
insert into Product(product_name, price, quantity)
VALUES ('juice', 300, 25);
insert into Product(product_name, price, quantity)
VALUES ('bubble', 100, 60);